<?php
/**
 * Description :
 *
 * PHP version 5
 *
 * @category View
 * @package  No
 * @author   Maxime GROSSET <contact@mail.com>
 * @license  tag in file comment
 * @link     No
 */
?>

<div class="diapo_shuffle">
    <div class="info"></div>

    <div class="options">
        Folder :
        <input class="custom_folder" type="text">
        <input class="start" type="button" value="start">
        <input class="stop" type="button" value="stop">
    </div>

    <div class="view"></div>
</div>

<script type="text/javascript">
curl([
    'jquery',
    'App/diapoShuffle'
], function ($, DiapoShuffle) {
    'use strict';
    DiapoShuffle.init();
});
</script>