<?php
/**
 * Description :
 *
 * PHP version 5
 *
 * @category View
 * @package  No
 * @author   Maxime GROSSET <contact@mail.com>
 * @license  tag in file comment
 * @link     No
 */
?>

<div class="diapo_shuffle">
    <div class="ctn_info"></div>

    <div class="ctn_options">
        Folder :
        <input class="text_custom_folder_options text_options" type="text"/>
        <input class="btn_start_options btn_options" type="button" value="start"/>
        <input class="btn_stop_options btn_options" type="button" value="stop"/>
        <input class="btn_pause_options btn_options" type="button" value="pause"/>
    </div>

    <div class="ctn_view"></div>
</div>
