<?php
/**
 * Description :
 *
 * PHP version 5
 *
 * @category View
 * @package  No
 * @author   Maxime GROSSET <contact@mail.com>
 * @license  tag in file comment
 * @link     No
 */
?>
<script type="text/javascript" src="/js/App/diapoShuffle.js"></script>

<div class="diapo_shuffle">
    <div class="info"></div>

    <div class="options">
        Folder :
        <input class="custom_folder" type="text">
        <input class="start" type="button" value="start">
        <input class="stop" type="button" value="stop">
    </div>

    <div class="view"></div>
</div>